### ISSUE TITLE
[Question]JNI error occurs when running the demo project of PA1

### ISSUE THREAD

**Issue by ywucr** [CastleLab/COMP3021-2020Fall-PA1-Student-Version#6]
Hello,
I got a problem when trying to run the demo project, the Powershell showed the message below

> PS D:\hkust\大四上\COMP3021\PA\PA1\COMP3021-2020Fall-PA1-Student-Version\artifacts> java -jar PA1_obfuscated.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: castle/comp3021/assignment/Main has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)

![Q1](https://user-images.githubusercontent.com/56708723/94163205-27017300-feba-11ea-9a2c-a7fa1f751b21.png)
I wonder what can I do to fix this error. 
Thank you!

**Comment by Troublor** [comment]
You are not using Java 14 to run the obfuscated version. Please check your java version by `java --version`.

**Comment by ywucr** [comment]
I hava download a new Java 14 environment and set it successfully. Thank you!
However I find that the demo project have some mess codes where should show the piece labels. As the pic shown below.
![Q1-1](https://user-images.githubusercontent.com/56708723/94171137-7ac48a00-fec3-11ea-914a-eebaa6b5b8c7.png)
One of my friends have the same problem as me. So I wanna know how can we fix this. 
Really appreciate!

**Comment by Troublor** [comment]
Check the [FAQ](https://github.com/CastleLab/COMP3021-2020Fall-PA1-Student-Version/blob/master/FAQ.md#q6-why-does-the-obfuscated-version-print-a-lot-of-corrupted-characters-like-34mk0m-34ma0m-in-the-output)

**Comment by ywucr** [comment]
Thank you!
